V0.4.0 update
moddevices/cc-fw-footswitch pull request #1
Opened 2020-11-23 13:27 UTC by AdamBuijks42

Features: 
* Momentary assignments
* Tap-Tempo
* LED cycling for lists
* Static LED for lists blinks
* Bidirectional communication - Value set

2020-11-23 14:17 UTC, Janjhl commented on src/hardware.h
> +int hw_settings_mode(void);
This function is never called, leftover code perhaps?

2020-11-23 14:24 UTC, Janjhl commented on src/util.c
> +    while (1)
copy paste error?
This should not be here

2020-11-23 14:24 UTC, Janjhl commented on src/util.h
> +void settings_screen_run(void);
This function is not used, old code?

2020-11-23 14:25 UTC, Janjhl commented on state
> +src/hardware.c:84:            if (button->state == BUTTON_RELEASED)
accidental file creation?

2020-11-23 14:26 UTC, Janjhl commented on Makefile
> +
let's leave the debug option, changing to Os is fine

2020-11-23 14:27 UTC, Janjhl requested changes
Small changes needed, as there is still some unused code
The rest seems ok!

2020-11-24 10:52 UTC, AdamBuijks42 commented
The requested changes should be fixed now.

2020-11-24 11:03 UTC, falkTX commented on src/util.h
> +#ifndef SETTINGS_H
this should be `UTILS_H`

2020-11-26 16:51 UTC, Janjhl approved these changes

2020-11-26 16:52 UTC, merged